### ISSUE TITLE
Sources should only be moveable on the shell

### ISSUE THREAD

**Issue by Jindorf** [Jindorf/HoloOSCV2#7]
Sources are currently moveable in all directions and whereaver the user wants. They should only be movable on the shell, so they should always keep the same distance to the (0,0,0) of the shell

**Comment by derTino89** [comment]
On the Prefab "Source" in the Manipulationhandler under "Constraints" you can choose "Constraint on Movement: Fix Distance from Head"
This doesnt work very well, even if you set the camera to 0,0,0.....but I thought maybe the function in the script may be the key, so that we change it and add "fix distance from centre." 
The original function is located in the TwoHandMoveLogic.cs
